### ISSUE TITLE
Alternative mode that removes whitespace

### ISSUE THREAD

**Issue by yyx990803** [leebyron/flow-remove-types#12]
In some cases I do want to remove the whitespace for better looking output (in particular, unlike babel, buble preserves the whitespaces after transpiling), which is currently not possible.

I've managed to create a fork that does so with sourcemap support using https://github.com/rich-harris/magic-string - wondering if we can add an option to enable this:

``` js
var { code, map } = flowRemoveTypes(input, {
  whitespace: false
});
```

If this looks like a good idea, I'll open a PR. `rollup-plugin-flow` will also need to be updated to accommodate this option.

**Comment by leebyron** [comment]
I think this is a cool idea, but the dependency on magic-string is probably not necessary. If this option was provided then it would just skip the step of adding the whitespace to the transformed source.

Source map support is perhaps another story - I don't know much about how they're generated actually, but I'd be surprised if it was very complicated to make a simplified form that only supported the removal of regions like this lib does.

**Comment by yyx990803** [comment]
@leebyron is performance the primary concern for the magicstring dependency? In my usage I didn't see noticeable perf loss using it - the whole build is still like 100% faster than the babel equivalent.

**Comment by rasmk** [comment]
Whitespace-removal would also be nice to have to satisfy some ESLint rules (no whitespace before ;, etc.)

**Comment by leebyron** [comment]
Perf isn't the primary concern, I like magic string. I think it's worth investigating what the most simple solution is. I just want to avoid using a sledgehammer for a nail.

@rasmk - I highly suggest running eslint on your original code and not the output of this or any other code transformer. Eslint is designed to help people write legible code, not transformers.

If you use a plugin for eslint that provides a parser thats aware of Flow (babel-eslint is a great one) then eslint should give you useful information again.

**Comment by leebyron** [comment]
Sorry for letting this sit - I just put up a PR which introduces this mode and includes source map support - I'd love your feedback @yyx990803
