### ISSUE TITLE
flow-remove-types with gulp task?

### ISSUE THREAD

**Issue by litan1106** [leebyron/flow-remove-types#13]
Any example of using flow-remove-types with gulp task?

**Comment by leebyron** [comment]
Check out https://github.com/leebyron/flow-remove-types#get-started for both a shell transformer (pipe stdin and get transform on stdout) and javascript API (string in, string out) for running flow-remove-types.

I don't have that much experience with gulp, but if you can call shell scripts or run javascript from it, then probably one of those two approaches will work out just fine!

My best guess is to use gulp's through streams API, perhaps something like this?

```js
var through = require('through2')

gulp.task('flow-remove-types', () => {
  return gulp.src('src/**/*.js')
    .pipe(through.obj((file, enc, cb) => {
      file.contents = new Buffer(flowRemoveTypes(file.contents.toString('utf8')))
      cb(null, file);
    }))
})
```

**Comment by leebyron** [comment]
To anyone who ends up here - `v1.1.0` introduced a breaking change which requires the example code above to be slightly different:

```js
var flowRemoveTypes = require('flow-remove-types')
var through = require('through2')

gulp.task('flow-remove-types', () => {
  return gulp.src('src/**/*.js')
    .pipe(through.obj((file, enc, cb) => {
      file.contents = new Buffer(flowRemoveTypes(file.contents.toString('utf8')).toString())
      cb(null, file);
    }))
})
```
