### ISSUE TITLE
Nested File Structures Fail

### ISSUE THREAD

**Issue by Smolations** [leebyron/flow-remove-types#16]
So, I'm working on a project that uses the CST project. That project has very little documentation, so I wanted to see if I could generate some for local development. ESDoc was giving the best results, but it was erroring on many files because the project is using flow for type checking. So I grabbed this module and set it on the src directory in the cst repo and almost immediately encountered an error. It was telling me that a file was not found, and that file was supposed to be the file created by this module! Ultimately, to get the desired results, I had to create the empty directory tree in the destination directory that matched the directory tree in the source directory. After doing that, the command succeeded without issue:

```
$ flow-remove-types src/ --out-dir src-unflowed/
src/Parser.js
 ↳ src-unflowed/Parser.js
src/Traverse.js
 ↳ src-unflowed/Traverse.js
src/elementTree.js
 ↳ src-unflowed/elementTree.js
src/index.js
 ↳ src-unflowed/index.js
src/visitorKeys.js
 ↳ src-unflowed/visitorKeys.js
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'src-unflowed/elements/Element.js'
  ...
```
```
// not using -p to illustrate all dirs with files in them
$ mkdir src-unflowed/elements
$ mkdir src-unflowed/elements/types
$ mkdir src-unflowed/elements/types/utils
$ mkdir src-unflowed/plugins
$ mkdir src-unflowed/plugins/scopes
$ mkdir src-unflowed/utils

// then all files succeeded
$ flow-remove-types src/ --out-dir src-unflowed/
src/Parser.js
 ↳ src-unflowed/Parser.js
src/Traverse.js
 ↳ src-unflowed/Traverse.js
src/elementTree.js
 ↳ src-unflowed/elementTree.js
src/index.js
 ↳ src-unflowed/index.js
src/visitorKeys.js
 ↳ src-unflowed/visitorKeys.js
src/elements/Element.js
 ↳ src-unflowed/elements/Element.js
src/elements/ElementAssert.js
 ↳ src-unflowed/elements/ElementAssert.js
...
```

**Comment by leebyron** [comment]
That's definitely strange! I fixed a similar bug a few months ago, so you should make sure you're using a relatively recent version of the module. Also, could you include a stack trace? Otherwise it's hard to debug the issue

**Comment by Smolations** [comment]
Well I literally installed the lib 15 minutes ago, so I can only assume it's up-to-date. 😋 

Here's the full stack trace for ya:
```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'src-unflowed/elements/Element.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.<anonymous> (/usr/local/nvm/versions/node/v4.4.4/lib/node_modules/flow-remove-types/flow-remove-types:155:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

**Comment by leebyron** [comment]
Awesome thank you!

Based on this I found what looked like a dubious line that would be related to this and pushed a new rev to npm just now, please give it a test!

**Comment by Smolations** [comment]
Wow, that was quick!  Awesome, thank you! 👏
