### ISSUE TITLE
Flow-remove-types does not handle functions/object without explicit argument/key names

### ISSUE THREAD

**Issue by mourner** [leebyron/flow-remove-types#18]
```js
// works
type A = {[key: string]: string};
type B = (foo: string) => string;

// works in flow, but flow-remove-types fails
type A = {[string]: string};
type B = (string) => string;
```

Flow documentation is not clear on the syntax and whether omitting names like this should be allowed, but Flow 0.35 parses such definitions without any errors. So `flow-remove-types` probably should too. cc @leebyron

**Comment by hzoo** [comment]
@mourner this is a new flow feature - it's not supported since babylon just added it and it's not released yet either https://github.com/babel/babylon/pull/197

**Comment by mourner** [comment]
@hzoo awesome, thanks!

**Comment by hzoo** [comment]
It's possible that flow-remove-types may need it's own changes after we release (soon) but just fyi yeah

**Comment by hzoo** [comment]
https://twitter.com/TschinderDaniel/status/798916219738976256 we released https://github.com/babel/babylon/releases/tag/v6.14.0 so install babylon again and check again?
