### ISSUE TITLE
Building up the string vs replacing the types with spaces

### ISSUE THREAD

**Issue by hzoo** [leebyron/flow-remove-types#2]
I was just wondering whether it could be faster to take the original source and just replace the parts given start/end with spaces rather than appending to a string from scratch? Might need to do a simple test for it

**Comment by leebyron** [comment]
Great idea

**Comment by leebyron** [comment]
Suggestions on which mechanism for replacing parts in the original string? Since strings are immutable in JavaScript, I assume you're talking about transferring it into a different form first?

**Comment by hzoo** [comment]
Yeah not sure if you could change it into an array and do a splice..

**Comment by leebyron** [comment]
I tried out building up an array of characters, but that was actually much slower. Considered Buffer/TypedArray but that poses issues for multi-byte UTF8 characters.

Closing this out, but thanks again for the idea to explore! Let me know if you come up with something speedy.

**Comment by hzoo** [comment]
Ok I tried it out just because but it's probably not faster haha https://github.com/hzoo/flow-remove-types/commit/d3282744ba8194900d6581817d040e68d0a0d8d9 - also not doing the new lines correctly atm. I guess string concat is a lot better (and simpler)
